//Portugal

const planoNumeracaoPT = [
  ["00", "Indicativo para acesso internacional"],
  ["01-09", "Reservados para uso futuro"],
  ["1", "Números curtos"],
  ["2", "Serviço telefónico acessível ao público em local fixo"],
  ["3", "Serviços nómadas"],
  ["4", "Livre"],
  ["5", "Reservado para eventual expansão"],
  ["6", "Serviços de audiotexto, de acesso a redes de dados etc."],
  [
    "7",
    "Serviços de redes privativas de voz, de acesso universal, de carácter utilitário de tarifa majorada de tarifa única por chamada e de números de encaminhamento interoperadores",
  ],
  [
    "8",
    "Serviços de chamadas grátis para o chamador, de chamadas com custos partilhados, de cartão virtual de chamadas, de número pessoal",
  ],
  ["9", "Serviços de comunicações móveis"],
];

const indicativosTlfFixoPT = [
  ["Lisboa", "21"],
  ["Porto", "22"],
  ["Mealhada", "231"],
  ["Viseu", "232"],
  ["Figueira da Foz", "233"],
  ["Aveiro", "234"],
  ["Arganil", "235"],
  ["Pombal", "236"],
  ["Seia", "238"],
  ["Coimbra", "239"],
  ["Abrantes", "241"],
  ["Ponte de Sor", "242"],
  ["Santarém", "243"],
  ["Leiria", "244"],
  ["Portalegre", "245"],
  ["Torres Novas", "249"],
  ["Valença", "251"],
  ["Vila Nova de Famalicão", "252"],
  ["Braga", "253"],
  ["Lamego", "254"],
  ["Penafiel", "255"],
  ["S. João da Madeira", "256"],
  ["Viana do Castelo", "258"],
  ["Vila Real", "259"],
  ["Torres Vedras", "261"],
  ["Caldas da Rainha", "262"],
  ["Vila Franca de Xira", "263"],
  ["Setúbal", "265"],
  ["Évora", "266"],
  ["Estremoz", "268"],
  ["Santiago do Cacém", "269"],
  ["Guarda", "271"],
  ["Castelo Branco", "272"],
  ["Bragança", "273"],
  ["Proença-a-nova", "274"],
  ["Covilhã", "275"],
  ["Chaves", "276"],
  ["Idanha-a-Nova", "277"],
  ["Mirandela", "278"],
  ["Moncorvo", "279"],
  ["Tavira", "281"],
  ["Portimão", "282"],
  ["Odemira", "283"],
  ["Beja", "284"],
  ["Moura", "285"],
  ["Castro Verde", "286"],
  ["Faro", "289"],
  ["Funchal", "291"],
  ["Horta", "292"],
  ["Angra do Heroísmo", "295"],
  ["Ponta Delgada", "296"],
  ["São Miguel", "296"],
];

const indicativosTelemovel = [
  ["MEO", "96"],
  ["MEO", "9240"],
  ["MEO", "9244"],
  ["MEO", "925"],
  ["MEO", "927"],
  ["NOS", "93"],
  ["Vodafone", "91"],
  ["Vodafone", "921"],
];

// nif data
const validationSets = {
  one: ["1", "2", "3", "5", "6", "8"],
  two: ["45", "70", "71", "72", "74", "75", "77", "79", "90", "91", "98", "99"],
};

const codigosPostal = [
  ["Lisboa", "10"],
  ["Lisboa", "11"],
  ["Lisboa", "12"],
  ["Lisboa", "13"],
  ["Lisboa", "14"],
  ["Lisboa", "15"],
  ["Lisboa", "16"],
  ["Lisboa", "17"],
  ["Lisboa", "18"],
  ["Lisboa", "19"],
  ["Santarém", "20"],
  ["Coruche", "21"],
  ["Abrantes", "22"],
  ["Tomar", "23"],
  ["Leiria", "24"],
  ["Caldas da Rainha", "25"],
  ["Vila Franca de Xira", "26"],
  ["Amadora", "27"],
  ["Almada", "28"],
  ["Setúbal", "29"],
  ["Coimbra", "30"],
  ["Pombal", "31"],
  ["Lousã", "32"],
  ["Arganil", "33"],
  ["Oliveira do Hospital", "34"],
  ["Viseu", "35"],
  ["Castro Daire", "36"],
  ["São João da Madeira", "37"],
  ["Aveiro", "38"],
  ["Porto", "40"],
  ["Porto", "41"],
  ["Porto", "42"],
  ["Porto", "43"],
  ["Vila Nova de Gaia", "44"],
  ["Espinho", "45"],
  ["Amarante", "46"],
  ["braga", "47"],
  ["Guimarães", "48"],
  ["Viana do Castelo", "49"],
  ["Vila Real", "50"],
  ["Lamego", "51"],
  ["Mogadouro", "52"],
  ["Bragança", "53"],
  ["Chaves", "54"],
  ["Castelo Branco", "60"],
  ["Sertã", "61"],
  ["Covilhã", "62"],
  ["Guarda", "63"],
  ["Pinhel", "64"],
  ["Évora", "70"],
  ["Estremoz", "71"],
  ["Reguengos de Monsaraz", "72"],
  ["Portalegre", "73"],
  ["Ponte de Sôr", "74"],
  ["Vila Nova de Santo André", "75"],
  ["Aljustrel", "76"],
  ["Almodôvar", "77"],
  ["Beja", "78"],
  ["Faro", "80"],
  ["Loulé", "81"],
  ["Albufeira", "82"],
  ["Silves", "83"],
  ["Lagoa", "84"],
  ["Portimão", "85"],
  ["Lagos", "86"],
  ["Olhão", "87"],
  ["Tavira", "88"],
  ["Vila Real de Santo António", "89"],
  ["Funchal", "90"],
  ["Santa Cruz", "91"],
  ["Machico", "92"],
  ["Câmara de Lobos", "93"],
  ["Porto Santo", "94"],
  ["Ponta Delgada", "95"],
  ["Ribeira Grande", "96"],
  ["Angra do Heroísmo", "97"],
  ["Velas", "98"],
  ["Horta", "99"],
];

//Brazil

//Angola

//Moçambique

//Guiné-Bissau

//Timor-Leste

//Cabo Verde

//São Tomé e Principe

module.exports = {
  indicativosTlfFixoPT,
  planoNumeracaoPT,
  indicativosTelemovel,
  validationSets,
  codigosPostal
};
